GET http://localhost:5174/users/login
###
GET http://localhost:5174/users/logout
###
POST http://localhost:5174/users/register
Content-Type:application/json

{
    "name": "username",
    "email": "email@gmail.com",
    "password": "username123"
}
###
POST http://localhost:5174/users/login
Content-Type:application/json

{
    "email": "email@gmail.com",
    "password": "username123"
}